### ISSUE TITLE
Biomes o' Plenty wood post issue

### ISSUE THREAD

**Issue by Shinisuryu** [jaquadro/GardenCollection#9] opened 2015-01-07 22:05 UTC
When trying to make wood posts with BoP woods, they end up as posts of something completely different. Magic wood makes Celestial Crystal posts and Redwood makes ender amethyst ore posts for two examples.

![2015-01-07_14 05 04](https://cloud.githubusercontent.com/assets/3065344/5654268/440a6bf8-9676-11e4-9acc-ce5741a6bb5d.png)
![2015-01-07_14 05 21](https://cloud.githubusercontent.com/assets/3065344/5654269/440aea7e-9676-11e4-9a9f-17b7d82a5ddc.png)

**Comment by jaquadro** [comment] 2015-02-09 03:31
Thanks for the report.  I couldn't reproduce it originally, but I discovered that it would happen if ID mappings in a world did not match the mappings when the Minecraft client first loads.

These recipes have been reworked to use the world-specific mappings.  This should be fixed in 1.2.3.

**Closed by jaquadro** 2015-02-09 03:31 UTC

**Comment by Shinisuryu** [comment] 2015-02-09 05:18
Thanks!
